sudo: false
language: scala
scala:
  - 2.12.12
  - 2.13.3
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
jdk:
  - openjdk11
  - openjdk13

after_success:
  - bash <(curl -s https://codecov.io/bash)